-- MySQL Script generated by MySQL Workbench
-- Tue Nov 12 08:44:04 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema szakdolgozatotthon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema szakdolgozatotthon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `szakdolgozatotthon` DEFAULT CHARACTER SET utf8 ;
USE `szakdolgozatotthon` ;

-- -----------------------------------------------------
-- Table `szakdolgozatotthon`.`beallitasok`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `szakdolgozatotthon`.`beallitasok` ;

CREATE TABLE IF NOT EXISTS `szakdolgozatotthon`.`beallitasok` (
  `iskolanev` VARCHAR(255) NOT NULL,
  `igazgatonev` VARCHAR(255) NOT NULL,
  `iskolacim` VARCHAR(255) NOT NULL,
  `ev` VARCHAR(255) NOT NULL)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `szakdolgozatotthon`.`beosztasok`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `szakdolgozatotthon`.`beosztasok` ;

CREATE TABLE IF NOT EXISTS `szakdolgozatotthon`.`beosztasok` (
  `beosztasid` INT(11) NOT NULL,
  `nev` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`beosztasid`))
ENGINE = MyISAM
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `szakdolgozatotthon`.`csengetesirend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `szakdolgozatotthon`.`csengetesirend` ;

CREATE TABLE IF NOT EXISTS `szakdolgozatotthon`.`csengetesirend` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ora` INT(2) NOT NULL,
  `kezdes` VARCHAR(5) NOT NULL,
  `vege` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `szakdolgozatotthon`.`dolgozatok`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `szakdolgozatotthon`.`dolgozatok` ;

CREATE TABLE IF NOT EXISTS `szakdolgozatotthon`.`dolgozatok` (
  `dolgozatid` INT(11) NOT NULL AUTO_INCREMENT,
  `utvonal` VARCHAR(255) NOT NULL,
  `jegyek_jegyid` INT(11) NOT NULL,
  PRIMARY KEY (`dolgozatid`, `jegyek_jegyid`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_dolgozatok_jegyek1_idx` ON `szakdolgozatotthon`.`dolgozatok` (`jegyek_jegyid` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `szakdolgozatotthon`.`haladasi_naplo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `szakdolgozatotthon`.`haladasi_naplo` ;

CREATE TABLE IF NOT EXISTS `szakdolgozatotthon`.`haladasi_naplo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `datum` DATE NOT NULL,
  `hanyadik_ora` INT(2) NOT NULL,
  `osztalyid` INT(7) NOT NULL,
  `tantargyid` INT(7) NOT NULL,
  `tevekenyseg` VARCHAR(255) NOT NULL,
  `tanarid` INT(7) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `szakdolgozatotthon`.`hianyzasok`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `szakdolgozatotthon`.`hianyzasok` ;

CREATE TABLE IF NOT EXISTS `szakdolgozatotthon`.`hianyzasok` (
  `hianyzasid` INT(8) NOT NULL AUTO_INCREMENT,
  `diakid` INT(7) NOT NULL,
  `tanarid` INT(7) NOT NULL,
  `hianyzas_datum` DATE NOT NULL,
  `hianyzas_tipus` INT(1) NOT NULL,
  `statusz` INT(1) NOT NULL,
  `rogz_datum` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`hianyzasid`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `szakdolgozatotthon`.`jegyek`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `szakdolgozatotthon`.`jegyek` ;

CREATE TABLE IF NOT EXISTS `szakdolgozatotthon`.`jegyek` (
  `jegyid` INT(11) NOT NULL AUTO_INCREMENT,
  `kiadta` INT(7) NOT NULL,
  `kikapta` INT(7) NOT NULL,
  `idopont` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `jegy` INT(1) NOT NULL,
  `tantargyid` INT(3) NOT NULL,
  `jeloles` CHAR(1) NOT NULL,
  `megjegyzes` VARCHAR(255) NOT NULL,
  `dolgid` INT(9) NOT NULL,
  `dolgfajlid` INT(9) NOT NULL,
  PRIMARY KEY (`jegyid`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `szakdolgozatotthon`.`login`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `szakdolgozatotthon`.`login` ;

CREATE TABLE IF NOT EXISTS `szakdolgozatotthon`.`login` (
  `userid` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`userid`))
ENGINE = MyISAM
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `szakdolgozatotthon`.`orarend`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `szakdolgozatotthon`.`orarend` ;

CREATE TABLE IF NOT EXISTS `szakdolgozatotthon`.`orarend` (
  `oraid` INT(11) NOT NULL AUTO_INCREMENT,
  `osztalyid` INT(3) NOT NULL,
  `datum` DATE NOT NULL,
  `hanyadik_ora` INT(2) NOT NULL,
  `tantargyid` INT(4) NOT NULL,
  `teremid` INT(5) NOT NULL,
  `tanarid` INT(7) NOT NULL,
  PRIMARY KEY (`oraid`))
ENGINE = MyISAM
AUTO_INCREMENT = 57
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `szakdolgozatotthon`.`osztalyok`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `szakdolgozatotthon`.`osztalyok` ;

CREATE TABLE IF NOT EXISTS `szakdolgozatotthon`.`osztalyok` (
  `osztalyid` INT(11) NOT NULL AUTO_INCREMENT,
  `osztalynev` VARCHAR(255) NOT NULL,
  `haladasi_naplo_id` INT(11) NOT NULL,
  `orarend_oraid` INT(11) NOT NULL,
  PRIMARY KEY (`osztalyid`, `haladasi_naplo_id`, `orarend_oraid`))
ENGINE = MyISAM
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_osztalyok_haladasi_naplo1_idx` ON `szakdolgozatotthon`.`osztalyok` (`haladasi_naplo_id` ASC) VISIBLE;

CREATE INDEX `fk_osztalyok_orarend1_idx` ON `szakdolgozatotthon`.`osztalyok` (`orarend_oraid` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `szakdolgozatotthon`.`szulogyermek`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `szakdolgozatotthon`.`szulogyermek` ;

CREATE TABLE IF NOT EXISTS `szakdolgozatotthon`.`szulogyermek` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `szuloid` INT(8) NOT NULL,
  `gyermekid` INT(8) NOT NULL,
  `hasznalt` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `szakdolgozatotthon`.`tantargyak`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `szakdolgozatotthon`.`tantargyak` ;

CREATE TABLE IF NOT EXISTS `szakdolgozatotthon`.`tantargyak` (
  `tantargyid` INT(11) NOT NULL AUTO_INCREMENT,
  `nev` VARCHAR(255) NOT NULL,
  `megjegyzes` VARCHAR(255) NOT NULL,
  `orarend_oraid` INT(11) NOT NULL,
  `jegyek_jegyid` INT(11) NOT NULL,
  `haladasi_naplo_id` INT(11) NOT NULL,
  PRIMARY KEY (`tantargyid`, `orarend_oraid`, `jegyek_jegyid`, `haladasi_naplo_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_tantargyak_orarend1_idx` ON `szakdolgozatotthon`.`tantargyak` (`orarend_oraid` ASC) VISIBLE;

CREATE INDEX `fk_tantargyak_jegyek1_idx` ON `szakdolgozatotthon`.`tantargyak` (`jegyek_jegyid` ASC) VISIBLE;

CREATE INDEX `fk_tantargyak_haladasi_naplo1_idx` ON `szakdolgozatotthon`.`tantargyak` (`haladasi_naplo_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `szakdolgozatotthon`.`termek`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `szakdolgozatotthon`.`termek` ;

CREATE TABLE IF NOT EXISTS `szakdolgozatotthon`.`termek` (
  `teremid` INT(11) NOT NULL AUTO_INCREMENT,
  `nev` VARCHAR(5) NOT NULL,
  `megjegyzes` VARCHAR(255) NOT NULL,
  `orarend_oraid` INT(11) NOT NULL,
  PRIMARY KEY (`teremid`, `orarend_oraid`))
ENGINE = MyISAM
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_termek_orarend1_idx` ON `szakdolgozatotthon`.`termek` (`orarend_oraid` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `szakdolgozatotthon`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `szakdolgozatotthon`.`users` ;

CREATE TABLE IF NOT EXISTS `szakdolgozatotthon`.`users` (
  `userid` INT(7) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `szulnev` VARCHAR(255) NOT NULL,
  `dob` DATE NOT NULL,
  `szulhely` VARCHAR(255) NOT NULL,
  `taj` VARCHAR(9) NOT NULL,
  `tel` VARCHAR(11) NOT NULL,
  `irsz` INT(4) NOT NULL,
  `lakcim` VARCHAR(255) NOT NULL,
  `osztalyid` VARCHAR(11) NOT NULL,
  `foto_link` VARCHAR(200) NOT NULL,
  `beosztas` INT(1) NOT NULL,
  `osztalyok_osztalyid` INT(11) NOT NULL,
  `orarend_oraid` INT(11) NOT NULL,
  `szulogyermek_id` INT(10) NOT NULL,
  `szulogyermek_id1` INT(10) NOT NULL,
  `login_userid` INT(11) NOT NULL,
  `haladasi_naplo_id` INT(11) NOT NULL,
  `users_userid` INT(7) NOT NULL,
  `users_osztalyok_osztalyid` INT(11) NOT NULL,
  `users_orarend_oraid` INT(11) NOT NULL,
  `users_szulogyermek_id` INT(10) NOT NULL,
  `users_szulogyermek_id1` INT(10) NOT NULL,
  `users_login_userid` INT(11) NOT NULL,
  `users_haladasi_naplo_id` INT(11) NOT NULL,
  `hianyzasok_hianyzasid` INT(8) NOT NULL,
  `jegyek_jegyid` INT(11) NOT NULL,
  `jegyek_jegyid1` INT(11) NOT NULL,
  `uzenetek_uzenetid` INT(11) NOT NULL,
  `uzenetek_uzenetid1` INT(11) NOT NULL,
  `beosztasok_beosztasid` INT(11) NOT NULL,
  PRIMARY KEY (`userid`, `osztalyok_osztalyid`, `orarend_oraid`, `szulogyermek_id`, `szulogyermek_id1`, `login_userid`, `haladasi_naplo_id`, `users_userid`, `users_osztalyok_osztalyid`, `users_orarend_oraid`, `users_szulogyermek_id`, `users_szulogyermek_id1`, `users_login_userid`, `users_haladasi_naplo_id`, `hianyzasok_hianyzasid`, `jegyek_jegyid`, `jegyek_jegyid1`, `uzenetek_uzenetid`, `uzenetek_uzenetid1`, `beosztasok_beosztasid`))
ENGINE = MyISAM
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_users_osztalyok_idx` ON `szakdolgozatotthon`.`users` (`osztalyok_osztalyid` ASC) VISIBLE;

CREATE INDEX `fk_users_orarend1_idx` ON `szakdolgozatotthon`.`users` (`orarend_oraid` ASC) VISIBLE;

CREATE INDEX `fk_users_szulogyermek1_idx` ON `szakdolgozatotthon`.`users` (`szulogyermek_id` ASC) VISIBLE;

CREATE INDEX `fk_users_szulogyermek2_idx` ON `szakdolgozatotthon`.`users` (`szulogyermek_id1` ASC) VISIBLE;

CREATE INDEX `fk_users_login1_idx` ON `szakdolgozatotthon`.`users` (`login_userid` ASC) VISIBLE;

CREATE INDEX `fk_users_haladasi_naplo1_idx` ON `szakdolgozatotthon`.`users` (`haladasi_naplo_id` ASC) VISIBLE;

CREATE INDEX `fk_users_hianyzasok1_idx` ON `szakdolgozatotthon`.`users` (`hianyzasok_hianyzasid` ASC) VISIBLE;

CREATE INDEX `fk_users_jegyek1_idx` ON `szakdolgozatotthon`.`users` (`jegyek_jegyid` ASC) VISIBLE;

CREATE INDEX `fk_users_jegyek2_idx` ON `szakdolgozatotthon`.`users` (`jegyek_jegyid1` ASC) VISIBLE;

CREATE INDEX `fk_users_uzenetek1_idx` ON `szakdolgozatotthon`.`users` (`uzenetek_uzenetid` ASC) VISIBLE;

CREATE INDEX `fk_users_uzenetek2_idx` ON `szakdolgozatotthon`.`users` (`uzenetek_uzenetid1` ASC) VISIBLE;

CREATE INDEX `fk_users_beosztasok1_idx` ON `szakdolgozatotthon`.`users` (`beosztasok_beosztasid` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `szakdolgozatotthon`.`uzenetek`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `szakdolgozatotthon`.`uzenetek` ;

CREATE TABLE IF NOT EXISTS `szakdolgozatotthon`.`uzenetek` (
  `uzenetid` INT(11) NOT NULL AUTO_INCREMENT,
  `felado` INT(7) NOT NULL,
  `cimzett` INT(7) NOT NULL,
  `datum` DATETIME NOT NULL,
  `targy` VARCHAR(50) NOT NULL,
  `uzenet` VARCHAR(9999) NOT NULL,
  `statusz` INT(2) NOT NULL,
  PRIMARY KEY (`uzenetid`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
